# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

  ##########################
  ### EMAIL
  ##########################

  # For getting automatic emails when an error occurs
  # exception_recipients: List of all emails that should receive the notification
  # sender_address: Who the notification email will be from
  # email_prefix: What each email should be prefixed with
  exception_notifier:
    exception_recipients: '<%= ENV['EXCEPTION_RECIPIENTS'] %>'
    sender_address: '<%= ENV['EXCEPTION_SENDER_ADDRESS'] %>'
    email_prefix: '<%= ENV['EXCEPTION_EMAIL_PREFIX'] %>'

  # For setting up email - this example uses sendgrid
  smtp_settings:
    address: '<%= ENV['EMAIL_ADDRESS'] %>'
    port: <%= ENV['EMAIL_PORT'] %>
    user_name: '<%= ENV['EMAIL_USER_NAME'] %>'
    domain: '<%= ENV['EMAIL_DOMAIN'] %>'
    password: '<%= ENV['EMAIL_PASSWORD'] %>'
    authentication: <%= ENV['EMAIL_AUTHENTICATION'] %>
    return_path: '<%= ENV['EMAIL_RETURN_PATH'] %>'
    enable_starttls_auto: <%= ENV['EMAIL_ENABLE_STARTTLS_AUTO'] %>
    xsmtpapi: <%= ENV['EMAIL_CATEGORY'] %>

  # Intercepting email delivery - primarily for test purposes
  # deliver_email of 'true' means it will send email as expect.
  # deliver_email of 'false' means it will send to the specified email list.
  mail_intercept:
    deliver_email: <%= ENV['EMAIL_DELIVER'] %>
    email_list: '<%= ENV['EMAIL_LIST'] %>'
    
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
